Repository Techiral/A-Z-Python-Projects, pull requests merged in 2023-10, with the labels that each got.

#45 Add Socket Programming in S directory
  S/socket-programming/client.py
  S/socket-programming/server.py
Labels: good first issue, hacktoberfest-accepted

#44 Create Taskmanager.py
  Taskmanager.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#43 Created a project robo-speaker in R folder
  R/robo-speaker/main.py
  R/robo-speaker/readme.md
  R/robo-speaker/requirements.txt
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#41 Adding a description of the program to the README
  T/type-speed-tester/README.md
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#40 Create WebConverterApp.py
  W/ConverterWebApp.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#36 qrcode generator project
  Q/qrcode_encode_decode/QRcodedocumentation.jpg
  Q/qrcode_encode_decode/README.md
  Q/qrcode_encode_decode/qr_code.py
  Q/qrcode_encode_decode/requirements.txt
  Q/qrcode_encode_decode/text.jpg
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#35 Create rgb-hex convert
  C/convert-rgb-to-hex/README.md
  C/convert-rgb-to-hex/convert-rgb-to-hex.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#58 added 4 digit checker
  armstrong.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#57 Create Fibonacci.py
  F/Fibonacci.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#56 custom password generator using command line arguement
  C/custom-password-generator/README.md
  C/custom-password-generator/custom-password-generator.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#52 Create Model.py
  B/BinaryClassification/Model.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#49 A Personal Budget manager using Tkinter.
  P/Personal-Budget-manager/tkt.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#55 added Tic tac toe game
  H/hangman_game/hangman_art.py
  H/hangman_game/main.py
  H/hangman_game/word_list.py
  T/Tic-Tac-Toe/README.md
  T/Tic-Tac-Toe/main.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#51 Added Rebel Cipher Project to Folder R
  .DS_Store
  R/.DS_Store
  R/rebel-cipher/rebel_cipher.md
  R/rebel-cipher/rebel_cipher.pdf
  R/rebel-cipher/rebel_cipher.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#66 Create a sorting project
  S/sorting-project/.gitignore
  S/sorting-project/README.md
  S/sorting-project/app.py
  S/sorting-project/bubble.py
  S/sorting-project/insertion.py
  S/sorting-project/merge.py
  S/sorting-project/selection.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#67 added coffee machine project [hacktoberfest]
  C/coffee-machine/__pycache__/art.cpython-310.pyc
  C/coffee-machine/__pycache__/data.cpython-310.pyc
  C/coffee-machine/art.py
  C/coffee-machine/coffee-machine.md
  C/coffee-machine/coffee.py
  C/coffee-machine/data.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#70 Added Discord Bot which tells jokes - Hacktoberfest
  D/Discord Jokes Bot/bot.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#81 added a imageTosketch python project
  I/image-to-sketch/README.md
  I/image-to-sketch/dog.jpg
  I/image-to-sketch/image_to_sketch.py
  I/image-to-sketch/requirements.txt
  I/image-to-sketch/sketchDog.jpg
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#80 Add Word Art using python
  W/Word Art from an image/Word Art from an image.py
  W/Word Art from an image/google.png
  W/Word Art from an image/textfile.txt
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#78 Atm banking system using python OOP concepts
  A/Atm banking system/Atm.py
  A/Atm banking system/README.md
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#77 Create PythonPointers.py
  PythonPointers.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#88 Added Library Management System Code
  L/library-management-system/main.py
  L/library-management-system/readme.md
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#93 Create a ChatGPT based voice assistant
  C/chatgpt-based-voice-assistant/README.md
  C/chatgpt-based-voice-assistant/requirements.txt
  C/chatgpt-based-voice-assistant/voice-assistant.py
  README.md
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#92 Create word guessing game
  W/word guessing game
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#91 Create whatsapp birthday bot
  W/whatsapp birthday bot
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#90 Added notes app
  N/notes-app/README.md
  N/notes-app/functions.py
  N/notes-app/notes-app.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#138 Cover python based steganography tool
  C/Cover-STEG/README.md
  C/Cover-STEG/app.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#135 Create Longest-Subsequence-Without-Repetetion.py
  L/Longest-Subsequence-Without-Repetation.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#133 traveling salesman problem
  T/traveling-salesman-problem/tsp.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#132 Added my emoji game in E folder
  E/emojiGame/.DS_Store
  E/emojiGame/angryface.png
  E/emojiGame/coke.png
  E/emojiGame/coolface.png
  E/emojiGame/evilface.png
  E/emojiGame/feverface.png
  E/emojiGame/freezeface.png
  E/emojiGame/index.html
  E/emojiGame/index.js
  E/emojiGame/lco.png
  E/emojiGame/mark.png
  E/emojiGame/mindblownface.png
  E/emojiGame/sneezeface.png
  E/emojiGame/styles.css
  E/emojiGame/thinkingface.png
  E/emojiGame/vomitface.png
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#127 Create extract-ip-address-from-file-using-python
  extract-ip-address-from-file-using-python
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#126 Create python-program-for-pigeonhole-sort
  python-program-for-pigeonhole-sort
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#101 PR : Internet Speed Tracker
  I/internet-speed-tracker/README.md
  I/internet-speed-tracker/first_screen.png
  I/internet-speed-tracker/internet_speedtest.py
  I/internet-speed-tracker/output_screen.png
  I/internet-speed-tracker/requirements.txt
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#94 added a client-server tcp program
  S/server-client-tcp/client.py
  S/server-client-tcp/readme.md
  S/server-client-tcp/server.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#170 Added A/atbash-cipher and README
  A/atbash-ciper/README.md
  A/atbash-ciper/atbash-cipher.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#182 Added pomodoro timer project written in python
  P/pomodoro-timer/main.py
  P/pomodoro-timer/tomato.png
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#181 add: color-morph color conversion tool
  C/color-morph/README.md
  C/color-morph/colorMorph.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#171 added Alzheimer disease prediction model
  A/Alzheimer-Disease-Prediction-using-ML/AlzheimerPrediction.ipynb
  A/Alzheimer-Disease-Prediction-using-ML/oasis_longitudinal.csv
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#175 Feature/gaming apps
  G/general_simplified_games/Quiz_application.py
  G/general_simplified_games/number_guessing_game.py
  README.md
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#174 Item-detection using Yolov8 from image
  I/image_detection.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#167 Added Certificate generator using python under C folder
  .DS_Store
  C/.DS_Store
  C/certificate-generator/README.md
  C/certificate-generator/certificate.py
  C/certificate-generator/certificate_template.png
  C/certificate-generator/fontss.ttf
  C/certificate-generator/names.xlsx
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#191 Added binary search program
  B/Binary search/binary_search.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#190 Added heart disease prediction model.
  H/heart_disease_prediction_model/cleveland.csv
  H/heart_disease_prediction_model/framingham.csv
  H/heart_disease_prediction_model/heart.ipynb
Labels: hacktoberfest-accepted, Hacktoberfest

#188 added-largest-array-finder
  L/largest-array-finder/l-array-finder.py
Labels: hacktoberfest-accepted, Hacktoberfest

#192 Add basic blockchain and update README
  B/basic-blockchain/basic-blockchain.py
  README.md
Labels: hacktoberfest-accepted, Hacktoberfest

#185 Added us states game written in python
  U/us-states-quiz/50_states.csv
  U/us-states-quiz/blank_states_img.gif
  U/us-states-quiz/main.py
Labels: hacktoberfest-accepted, Hacktoberfest

#184 Added turtle-crossing game written in python
  T/turtle-crossing/car_manager.py
  T/turtle-crossing/main.py
  T/turtle-crossing/player.py
  T/turtle-crossing/scoreboard.py
Labels: hacktoberfest-accepted, Hacktoberfest

#183 Created A StopWatch Using Python.
  S/StopWatch In Python/Calculate.py
  S/StopWatch In Python/StopWatch.png
  S/StopWatch In Python/readme.md
Labels: hacktoberfest-accepted, Hacktoberfest

#169 Added a README.md file
  B/button-in-pygame/README.md
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#168 Improvised Rock Paper Scissors. Pull Req for Hacktoberfest.
  R/rock paper scissors/README.md
  R/rock paper scissors/main.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#166 Create Bubble_Sort.py
  B/Bubble_Sort.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#164 SplitWise machine-coding implementation in python
  S/splitwise/CalculationService.py
  S/splitwise/CalculationServiceImp.py
  S/splitwise/Expense.py
  S/splitwise/ExpenseController.py
  S/splitwise/README.md
  S/splitwise/SplitwiseDriver.py
  S/splitwise/User.py
  S/splitwise/UserController.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#162 code.py
  S/Split a list into nonprime & prime/code.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#161 Added a simple customizable quizzing app
  Q/Quiz-test.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#160 Added snake game written in python
  S/snake-game/food.py
  S/snake-game/main.py
  S/snake-game/scoreboard.py
  S/snake-game/snake.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#158 Added voice assistant project under Directory V
  V/voice-assistant/Readme.md
  V/voice-assistant/VoiceAssistant.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest

#157 Hacktoberfest update
  E/emojiGame/blackheart.png
  E/emojiGame/family.png
  E/emojiGame/heart.png
  E/emojiGame/index.html
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest
